testing on OSX

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -5,21 +5,42 @@ on:
     branches: [ main ]
   pull_request:
     branches: [ main ]
+  
+strategy:
+  matrix:
+    os: [ ubuntu-latest, macos-latest ]
 
 jobs:
   deploy:
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }} 
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: "3.x"
-      - name: Install dependencies
+
+      - name: Install Homebrew
+        run: |
+          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+
+      - name: Install Python Dependencies
         run: |
           python -m pip install --upgrade pip
           pip install setuptools wheel twine
-          sudo apt-get install swig
+
+      - name: Install Swig
+        shell: bash
+        run: |
+          if [ "$RUNNER_OS" == "Linux" ] ; then
+            sudo apt-get install swig
+          elif [ "$RUNNER_OS" == "macOS" ] ; then
+            brew install swig
+          else
+            echo "OS ERROR"
+            exit 1
+          fi
+
           cd Python/openmtpk &&
           make run-swig
           make compile 
