testing builds for cpp and python on linux and macos

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -29,14 +29,20 @@ jobs:
           python -m pip install --upgrade pip
           pip install setuptools wheel twine
 
-      - name: Install Swig and Headers
+          if [ "$RUNNER_OS" == "macOS" ] ; then
+          brew install python
+          else
+            echo "OS ERROR"
+            exit 1
+          fi
+
+      - name: Install Swig
         shell: bash
         run: |
           if [ "$RUNNER_OS" == "Linux" ] ; then
             sudo apt-get install swig
           elif [ "$RUNNER_OS" == "macOS" ] ; then
             brew install swig
-            xcode-select --install
           else
             echo "OS ERROR"
             exit 1
